# Generated by Django 4.2.11 on 2025-05-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='order',
        ),
    ]
