# Generated by Django 4.2.11 on 2025-05-14 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
