# Generated by Django 4.2.11 on 2025-05-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_rename_create_at_memo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
