# Generated by Django 4.2.11 on 2025-05-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_memo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='title',
        ),
    ]
