# Generated by Django 4.2.11 on 2025-05-14 07:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_date', models.DateTimeField()),
                ('map_directions', models.JSONField(blank=True, null=True)),
                ('meeting_directions', models.CharField(blank=True, max_length=255)),
                ('max_members', models.PositiveBigIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('delete_status', models.CharField(choices=[('UNDELETE', '삭제 안함'), ('DELETE', '삭제')], default='UNDELETE', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_meetings', to='books.book')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('member_status', models.CharField(choices=[('MEETING_ADMIN', '모임장'), ('MEETING_USER', '모임사용자')], default='MEETING_USER', max_length=20)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'meeting')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(related_name='joined_meetings', through='meeting.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['creator'], name='meeting_mee_creator_3460be_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['book'], name='meeting_mee_book_id_22dbac_idx'),
        ),
    ]
