# Generated by Django 4.2.11 on 2025-05-15 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='max_members',
            field=models.PositiveBigIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1, message='최대 인원은 1명 이상이어야 합니다.'), django.core.validators.MaxValueValidator(6, message='최대 인원은 6명을 초과할 수 없습니다.')]),
        ),
    ]
