# Generated by Django 4.2.11 on 2025-05-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_alter_meeting_max_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_directions',
            field=models.CharField(max_length=255),
        ),
    ]
