# Generated by Django 4.2.11 on 2025-05-13 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sender', models.BooleanField()),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('read_status', models.CharField(choices=[('UNREAD', '읽지 않음'), ('READ', '읽음')], default='UNREAD', max_length=10)),
                ('delete_status', models.CharField(choices=[('UNDELETE', '삭제 안함'), ('DELETE', '삭제')], default='UNDELETE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_partner', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
