# Generated by Django 4.2.11 on 2025-05-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
