# Generated by Django 4.2.11 on 2025-04-25 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='책이름')),
                ('content', models.TextField(verbose_name='내용')),
                ('author', models.CharField(max_length=100, verbose_name='저자')),
                ('link', models.CharField(max_length=200, verbose_name='책구매링크')),
                ('img', models.CharField(max_length=200, verbose_name='이미지URL')),
                ('best_seller_rank', models.CharField(max_length=50, verbose_name='베스트셀러순위')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
            ],
        ),
    ]
