# Generated by Django 4.2.11 on 2025-05-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.CharField(max_length=255, null=True, verbose_name='요약문'),
        ),
    ]
