# Generated by Django 4.2.11 on 2025-05-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
