# Generated by Django 4.2.11 on 2025-05-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_community_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='user_id',
            new_name='writer',
        ),
    ]
