# Generated by Django 4.2.11 on 2025-05-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_user_id_community_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='writer',
            new_name='user',
        ),
    ]
